#!/bin/bash


# Install required packages
func_install_prerequisites() {
    echo "Installing required packages..."
    apt-get update
    apt-get install -y \
        distcc \
        netcat-openbsd


}

func_preparation() {
    set -e

    source /.env
    ##################################################################################################
    # 1st file: hide engine
    # it is used to generate the config file which contains lots of distcc related environment variables
    RO_HIDE_SWITCHER_ENGINE_FILE="/usr/local/bin/distcc/.hide_distcc_switcher_engine.sh"
    # 2nd file: config file
    # it is used to store the config of distcc switcher
    # e.g., export DISTCC_HOSTS="192.168.xxxxx"
    RO_SWITCHER_CONFIG_FILE="/usr/local/bin/distcc/.distcc_switcher_config.sh"
    # 3rd file: surface switcher
    # it is used to control from top of all
    RO_SURFACE_SWITCHER_FILE="/usr/local/bin/distcc_switcher.sh"
    ##################################################################################################


    # 1. create the distcc directory
    sudo mkdir -p $(dirname ${RO_HIDE_SWITCHER_ENGINE_FILE})

    sudo touch ${RO_HIDE_SWITCHER_ENGINE_FILE}
    sudo touch ${RO_SWITCHER_CONFIG_FILE}
    sudo touch ${RO_SURFACE_SWITCHER_FILE}
}

# Generate the final switcher script
func_generate_switcher_script() {
    echo "Generating distcc scripts..."

    # 主控制脚本
    sudo tee ${RO_HIDE_SWITCHER_ENGINE_FILE} > /dev/null << EOF
#!/bin/bash
#==============================================================================
# Distcc Switcher Script
# Generated by install_distcc_switcher.sh
# Donot modify this file, it will be overwritten by install_distcc_switcher.sh
#
# Version: ${PROJECT_VERSION}
# Maintainer: ${PROJECT_MAINTAINER}
# Email: ${PROJECT_EMAIL}
# Copyright: ${PROJECT_COPYRIGHT}
# License: ${PROJECT_LICENSE}
#==============================================================================

#------------------------------------------------------------------------------
# Constants and configurations
#------------------------------------------------------------------------------
func_setup_environment() {
    set -e
    # set -x

    #------------------------------------------------------------------------------
    # System paths and directories
    #------------------------------------------------------------------------------

    #------------------------------------------------------------------------------
    # Distcc paths and configurations
    #------------------------------------------------------------------------------
    readonly RO_DISTCC_PROFILE_FILE="${RO_SWITCHER_CONFIG_FILE}"

    #------------------------------------------------------------------------------
    # Control switches
    #------------------------------------------------------------------------------
    ENABLE_HOST_TOOLCHAIN=0
    ENABLE_CROSS_TOOLCHAIN=1

    #------------------------------------------------------------------------------
    # Distcc behavior control
    #------------------------------------------------------------------------------
    # Performance settings
    readonly RO_DISTCC_VERBOSE="${DISTCC_VERBOSE:-0}"
    readonly RO_DISTCC_LOG_LEVEL="${DISTCC_LOG_LEVEL:-"warning"}"
    readonly RO_DISTCC_JOBS="${DISTCC_JOBS:-8}"
    readonly RO_DISTCC_TCP_CORK="${DISTCC_TCP_CORK:-1}"
    readonly RO_DISTCC_SAVE_TEMPS="${DISTCC_SAVE_TEMPS:-0}"
    readonly RO_DISTCC_FALLBACK="${DISTCC_FALLBACK:-1}"
    readonly RO_DISTCC_URL="${DISTCC_PORT:+${UBUNTU_SERVER_IP:+${UBUNTU_SERVER_IP}:${DISTCC_PORT}}}"
    readonly RO_DISTCC_HOSTS="\${RO_DISTCC_URL:-localhost/2}"
    readonly RO_ENABLE_PUMP_MODE="${ENABLE_PUMP_MODE:-0}"
    readonly RO_DISTCC_PATH="\${PATH}"

    readonly RO_CROSS_TOOLCHAIN_DIR="${SDK_INSTALL_PATH:+${SDK_INSTALL_PATH}/prebuilts/gcc/linux-x86/aarch64/gcc-arm-10.3-2021.07-x86_64-aarch64-none-linux-gnu/bin}"
    readonly RO_BACKUP_DIR="${VOLUMES_ROOT}/backup"

    #------------------------------------------------------------------------------
    # Toolchain configurations
    #------------------------------------------------------------------------------
    readonly RO_CROSS_TOOLCHAIN_NAMES=(
        "aarch64-none-linux-gnu"
        "aarch64-rockchip1031-linux-gnu"
    )
    readonly RO_TOOLCHAIN_COMMANDS=(
        "gcc"
        "g++"
        "c++"
        "cpp"
    )
}

#------------------------------------------------------------------------------
# Cross toolchain related functions
#------------------------------------------------------------------------------
func_setup_cross_toolchain() {
    if [ "\${ENABLE_CROSS_TOOLCHAIN}" -eq 0 ]; then
        echo "Cross toolchain distcc is disabled"
        return 0
    fi

    # # Check if distcc directory exists
    # if [ ! -d "\${RO_DISTCC_LINKS_DIR}" ]; then
    #     echo "Error: Distcc directory \${RO_DISTCC_LINKS_DIR} does not exist"
    #     echo "Please make sure distcc is properly installed"
    #     return 1
    # fi

    # echo "Setting up cross toolchain symlinks..."
    # cd \${RO_DISTCC_LINKS_DIR}

    for prefix in "\${RO_CROSS_TOOLCHAIN_NAMES[@]}"; do
        for cmd in "\${RO_TOOLCHAIN_COMMANDS[@]}"; do
            if [ -d "\${RO_CROSS_TOOLCHAIN_DIR}" ]; then
                sudo mkdir -p \${RO_BACKUP_DIR}
                sudo chown "\${DEV_USERNAME}:\${DEV_GROUP}" \${RO_BACKUP_DIR}
                cp -fv "\${RO_CROSS_TOOLCHAIN_DIR}/\${prefix}-\${cmd}" "\${RO_BACKUP_DIR}"
                rm -f "\${RO_CROSS_TOOLCHAIN_DIR}/\${prefix}-\${cmd}"
                ln -sf \$(which distcc) "\${RO_CROSS_TOOLCHAIN_DIR}/\${prefix}-\${cmd}"
            else
                echo "Error: Cross toolchain directory \${RO_CROSS_TOOLCHAIN_DIR} does not exist."
                echo -e "\tYou can exec this script again after the sdk of \${CONTAINER_NAME} has been cloned."

                return 1
            fi
        done
    done
}

func_restore_cross_toolchain() {
    echo "Cleaning cross toolchain symlinks..."
    for prefix in "\${RO_CROSS_TOOLCHAIN_NAMES[@]}"; do
        for cmd in "\${RO_TOOLCHAIN_COMMANDS[@]}"; do
            rm -f "\${RO_CROSS_TOOLCHAIN_DIR}/\${prefix}-\${cmd}"
            cp -fv "\${RO_BACKUP_DIR}/\${prefix}-\${cmd}" "\${RO_CROSS_TOOLCHAIN_DIR}"
        done
    done
}

#------------------------------------------------------------------------------
# Host toolchain related functions (reserved interfaces)
#------------------------------------------------------------------------------
func_setup_host_toolchain() {
    if [ "\${ENABLE_HOST_TOOLCHAIN}" -eq 0 ]; then
        echo "Host toolchain distcc is disabled"
        return 0
    fi
    echo "Empty now, will add host toolchain setup later"
}

func_restore_host_toolchain() {
    if [ "\${ENABLE_HOST_TOOLCHAIN}" -eq 0 ]; then
        return 0
    fi
    echo "Empty now, will add host toolchain cleanup later"
}

#------------------------------------------------------------------------------
# Environment variables setup
#------------------------------------------------------------------------------
func_setup_environment_vars() {
    echo "Setting up environment variables..."

    sudo tee \${RO_DISTCC_PROFILE_FILE} > /dev/null << EOPROFILE
# Set up distcc configuration
export DISTCC_HOSTS="\${RO_DISTCC_HOSTS:-localhost/2}"
export DISTCC_PATH="\${RO_DISTCC_PATH}"
export DISTCC_VERBOSE="\${RO_DISTCC_VERBOSE}"
export DISTCC_LOG_LEVEL="\${RO_DISTCC_LOG_LEVEL}"
export DISTCC_JOBS="\${RO_DISTCC_JOBS}"
export DISTCC_TCP_CORK="\${RO_DISTCC_TCP_CORK}"
export DISTCC_SAVE_TEMPS="\${RO_DISTCC_SAVE_TEMPS}"
export DISTCC_FALLBACK="\${RO_DISTCC_FALLBACK}"

# Enable pump mode if configured
if [ "\${RO_ENABLE_PUMP_MODE}" -eq 1 ]; then
    export PUMP_MODE=1
fi
EOPROFILE

    sudo chmod +x \${RO_DISTCC_PROFILE_FILE}

    # make all environments take effect
    if [ -f \${RO_DISTCC_PROFILE_FILE} ]; then
        source \${RO_DISTCC_PROFILE_FILE}
    else
        echo "Warning: Failed to create profile file"
        return 1
    fi
}

func_clean_environment() {
    echo "Cleaning environment..."
    sudo rm -f \${RO_DISTCC_PROFILE_FILE}
}

#------------------------------------------------------------------------------
# Main functionality functions
#------------------------------------------------------------------------------
func_enable_distcc() {
    # Enable cross toolchain
    if [ "\${ENABLE_CROSS_TOOLCHAIN}" -eq 1 ]; then
        func_setup_cross_toolchain
    fi

    # Enable host toolchain (reserved)
    if [ "\${ENABLE_HOST_TOOLCHAIN}" -eq 1 ]; then
        func_setup_host_toolchain
    fi

    func_setup_environment_vars
    echo -e "\ndistcc has been enabled with selected features!\n"
    echo "-------------------------------------------------------------------"
}

func_disable_distcc() {
    # Clean cross toolchain
    if [ "\${ENABLE_CROSS_TOOLCHAIN}" -eq 1 ]; then
        func_restore_cross_toolchain
    fi

    # Clean host toolchain (reserved)
    if [ "\${ENABLE_HOST_TOOLCHAIN}" -eq 1 ]; then
        func_restore_host_toolchain
    fi

    func_clean_environment
    echo "distcc has been disabled"
}

#------------------------------------------------------------------------------
# Usage function
#------------------------------------------------------------------------------
func_usage() {
    local script_name=\$(basename \${0})
    echo
    echo "Usage: \${script_name} {enable|disable}"
    echo -e "\n\n"
    echo "Current status: \$([ -f \${RO_DISTCC_PROFILE_FILE} ] && echo 'enabled' || echo 'disabled')"
    echo "Cross toolchain distcc: \$([ \${ENABLE_CROSS_TOOLCHAIN:-0} -eq 1 ] && echo 'enabled' || echo 'disabled')"
    echo "Host toolchain distcc: \$([ \${ENABLE_HOST_TOOLCHAIN:-0} -eq 1 ] && echo 'enabled' || echo 'disabled')"
    echo -e "\nYou have two ways to use distcc control:"
    echo -e "\n1. Using aliases (Recommended):"
    echo "   distcc-enable    # Enable distcc"
    echo "   distcc-disable   # Disable distcc"
    echo "   To activate aliases now: source /etc/profile.d/distcc_alias.sh"
    echo -e "\n2. Using the original script:"
    echo "   source /usr/local/bin/distcc_switcher.sh enable    # Enable distcc"
    echo "   source /usr/local/bin/distcc_switcher.sh disable   # Disable distcc"
    echo -e "\nNote: Aliases will be automatically available in new terminal sessions."
    echo
    return 1
}

func_check_prerequisites() {
    # # Check distcc executable
    # if [ ! -x "\${DISTCC_PATH}" ]; then
    #     echo "Error: distcc not found or not executable"
    #     return 1
    # fi

    # # Check distcc directory
    # if [ ! -d "\${RO_DISTCC_LINKS_DIR}" ]; then
    #     echo "Error: Distcc directory \${RO_DISTCC_LINKS_DIR} does not exist"
    #     return 1
    # fi

    return 0
}

func_ensure_root() {
    if [ "$(id -u)" -ne 0 ]; then
        echo "This script requires root privileges. Requesting sudo access..."
        exec sudo "\$0" "\$@"
    fi
}

main() {
    # Setup environment first
    func_setup_environment

    # Ensure root
    func_ensure_root

    # Check prerequisites
    if ! func_check_prerequisites; then
        echo "Error: distcc is not properly installed"
        exit 1
    fi

    echo -e "\nArgument count: \${#}\n"

    # Show usage if no arguments or help requested
    if [ "\${#}" -ne 1 ] || [ "\${1}" = "-h" ] || [ "\${1}" = "--help" ] || [ "\${1}" = "?" ]; then
        echo -e "\n\\\${#}=\${#}\n"
        func_usage
        exit 0
    fi

    # Process command
    case "\${1}" in
        "enable")
            func_enable_distcc
            ;;
        "disable")
            func_disable_distcc
            ;;
        *)
            echo "Error: Invalid command '\${1}'"
            func_usage
            exit 1
            ;;
    esac
}

# Execute main function with all script arguments
main "\$@"
EOF

    # 创建 enable 脚本
    sudo tee ${RO_SURFACE_SWITCHER_FILE} > /dev/null << EOF
#!/bin/bash
# Enable distcc with environment setup
func_enable_distcc() {
    ${RO_HIDE_SWITCHER_ENGINE_FILE} enable
    source ${RO_SURFACE_SWITCHER_FILE}
}

func_disable_distcc() {
    ${RO_HIDE_SWITCHER_ENGINE_FILE} disable
    # source ${RO_SURFACE_SWITCHER_FILE}
}

func_usage() {
    echo
    echo "###########################################################################################"
    echo -e "#\tInstallation completed. distcc control has been installed.                        #"
    echo "###########################################################################################"
    echo -e "\nTo use distcc control:"
    echo
    echo "   ${RO_SURFACE_SWITCHER_FILE} enable     # Enable distcc"
    echo "   ${RO_SURFACE_SWITCHER_FILE} disable    # Disable distcc"
    echo
}


main (){
    if [ "\${#}" -ne 1 ] || [ "\${1}" = "-h" ] || [ "\${1}" = "--help" ] || [ "\${1}" = "?" ]; then
        echo -e "\n\\\${#}=\${#}\n"
        func_usage
        exit 0
    fi

    case "\${1}" in
        "enable")
            func_enable_distcc
            ;;
        "disable")
            func_disable_distcc
            ;;
    esac
}

main "\$@"
EOF
}

func_set_permissions() {
    echo "Setting executable permissions..."
    sudo chmod +x ${RO_HIDE_SWITCHER_ENGINE_FILE}
    sudo chmod +x ${RO_SWITCHER_CONFIG_FILE}
    sudo chmod +x ${RO_SURFACE_SWITCHER_FILE}
}

# 修改使用说明
func_print_completion() {
    echo
    echo "###########################################################################################"
    echo -e "#\tInstallation completed. distcc control has been installed.                        #"
    echo "###########################################################################################"
    echo -e "\nTo use distcc control:"
    echo
    echo "   ${RO_SURFACE_SWITCHER_FILE} enable     # Enable distcc"
    echo "   ${RO_SURFACE_SWITCHER_FILE} disable    # Disable distcc"
    echo
}

# Main installation function
main() {
    # Step 1: Install prerequisites
    # func_install_prerequisites
    func_preparation

    # Step 2: Generate the switcher script
    func_generate_switcher_script

    # Step 3: Set proper permissions
    func_set_permissions

    # Step 4: Print completion message
    func_print_completion
}

# Execute main installation function
main "$@"