#!/bin/bash

set -e

source /.env

# Install required packages
func_install_prerequisites() {
    echo "Installing required packages..."
    apt-get update
    apt-get install -y \
        distcc \
        netcat-openbsd
}

# Generate the final switcher script
func_generate_switcher_script() {
    echo "Generating distcc_switcher.sh..."
cat > /usr/local/bin/distcc_switcher.sh << EOF
#!/bin/bash
#==============================================================================
# Distcc Switcher Script
# Generated by install_distcc_switcher.sh
# Donot modify this file, it will be overwritten by install_distcc_switcher.sh
#
# Version: ${PROJECT_VERSION}
# Maintainer: ${PROJECT_MAINTAINER}
# Email: ${PROJECT_EMAIL}
# Copyright: ${PROJECT_COPYRIGHT}
# License: ${PROJECT_LICENSE}
#==============================================================================

#------------------------------------------------------------------------------
# Constants and configurations
#------------------------------------------------------------------------------
func_setup_environment() {
    # set -e
    set -x

    #------------------------------------------------------------------------------
    # System paths and directories
    #------------------------------------------------------------------------------
    readonly SYSTEM_PROFILE_DIR="/etc/profile.d"
    readonly SYSTEM_BIN_DIR="/usr/lib"

    #------------------------------------------------------------------------------
    # Distcc paths and configurations
    #------------------------------------------------------------------------------
    readonly DISTCC_LINKS_DIR="\${SYSTEM_BIN_DIR}/distcc"
    readonly DISTCC_PROFILE_FILE="\${SYSTEM_PROFILE_DIR}/distcc.sh"
    readonly DISTCC_PATH="\$(which distcc)"

    #------------------------------------------------------------------------------
    # Control switches
    #------------------------------------------------------------------------------
    readonly ENABLE_HOST_TOOLCHAIN=0
    readonly ENABLE_CROSS_TOOLCHAIN=1

    #------------------------------------------------------------------------------
    # Distcc behavior control
    #------------------------------------------------------------------------------
    # Performance settings
    readonly DISTCC_VERBOSE="${DISTCC_VERBOSE:-0}"
    readonly DISTCC_LOG_LEVEL="${DISTCC_LOG_LEVEL:-"warning"}"
    readonly DISTCC_JOBS="${DISTCC_JOBS:-8}"
    readonly DISTCC_TCP_CORK="${DISTCC_TCP_CORK:-1}"
    readonly DISTCC_SAVE_TEMPS="${DISTCC_SAVE_TEMPS:-0}"
    readonly DISTCC_FALLBACK="${DISTCC_FALLBACK:-1}"
    readonly RO_DISTCC_URL="${DISTCC_PORT:+${UBUNTU_SERVER_IP:+${UBUNTU_SERVER_IP}:${DISTCC_PORT}}}"
    readonly RO_DISTCC_HOSTS="\${RO_DISTCC_URL:-localhost/2}"
    readonly ENABLE_PUMP_MODE="${ENABLE_PUMP_MODE:-0}"

    #------------------------------------------------------------------------------
    # Toolchain configurations
    #------------------------------------------------------------------------------
    readonly CROSS_TOOLCHAIN_NAMES=(
        "aarch64-none-linux-gnu"
        "aarch64-rockchip1031-linux-gnu"
    )
    readonly TOOLCHAIN_COMMANDS=(
        "gcc"
        "g++"
        "c++"
        "cpp"
    )
}

#------------------------------------------------------------------------------
# Cross toolchain related functions
#------------------------------------------------------------------------------
func_setup_cross_toolchain() {
    if [ "\${ENABLE_CROSS_TOOLCHAIN}" -eq 0 ]; then
        echo "Cross toolchain distcc is disabled"
        return 0
    fi

    # Check if distcc directory exists
    if [ ! -d "\${DISTCC_LINKS_DIR}" ]; then
        echo "Error: Distcc directory \${DISTCC_LINKS_DIR} does not exist"
        echo "Please make sure distcc is properly installed"
        return 1
    fi

    echo "Setting up cross toolchain symlinks..."
    cd \${DISTCC_LINKS_DIR}

    for prefix in "\${CROSS_TOOLCHAIN_NAMES[@]}"; do
        for cmd in "\${TOOLCHAIN_COMMANDS[@]}"; do
            sudo ln -sf \${DISTCC_PATH} "\${prefix}-\${cmd}"
        done
    done
}

func_restore_cross_toolchain() {
    echo "Cleaning cross toolchain symlinks..."
    for prefix in "\${CROSS_TOOLCHAIN_NAMES[@]}"; do
        for cmd in "\${TOOLCHAIN_COMMANDS[@]}"; do
            sudo rm -f "\${DISTCC_LINKS_DIR}/\${prefix}-\${cmd}"
        done
    done
}

#------------------------------------------------------------------------------
# Host toolchain related functions (reserved interfaces)
#------------------------------------------------------------------------------
func_setup_host_toolchain() {
    if [ "\${ENABLE_HOST_TOOLCHAIN}" -eq 0 ]; then
        echo "Host toolchain distcc is disabled"
        return 0
    fi
    echo "Empty now, will add host toolchain setup later"
}

func_restore_host_toolchain() {
    if [ "\${ENABLE_HOST_TOOLCHAIN}" -eq 0 ]; then
        return 0
    fi
    echo "Empty now, will add host toolchain cleanup later"
}

#------------------------------------------------------------------------------
# Environment variables setup
#------------------------------------------------------------------------------
func_setup_environment_vars() {
    echo "Setting up environment variables..."

    sudo tee \${DISTCC_PROFILE_FILE} > /dev/null << EOPROFILE
# Set up distcc configuration
export DISTCC_HOSTS="\${RO_DISTCC_HOSTS:-localhost/2}"

# Enable pump mode if configured
if [ "\${ENABLE_PUMP_MODE}" -eq 1 ]; then
    export PUMP_MODE=1
fi
EOPROFILE

    sudo chmod +x \${DISTCC_PROFILE_FILE}

    # make all environments take effect
    if [ -f \${DISTCC_PROFILE_FILE} ]; then
        source \${DISTCC_PROFILE_FILE}
    else
        echo "Warning: Failed to create profile file"
        return 1
    fi
}

func_clean_environment() {
    echo "Cleaning environment..."
    sudo rm -f \${DISTCC_PROFILE_FILE}
}

#------------------------------------------------------------------------------
# Main functionality functions
#------------------------------------------------------------------------------
func_enable_distcc() {
    # Enable cross toolchain
    if [ "\${ENABLE_CROSS_TOOLCHAIN}" -eq 1 ]; then
        func_setup_cross_toolchain
    fi

    # Enable host toolchain (reserved)
    if [ "\${ENABLE_HOST_TOOLCHAIN}" -eq 1 ]; then
        func_setup_host_toolchain
    fi

    func_setup_environment_vars
    echo "distcc has been enabled with selected features"
}

func_disable_distcc() {
    # Clean cross toolchain
    if [ "\${ENABLE_CROSS_TOOLCHAIN}" -eq 1 ]; then
        func_restore_cross_toolchain
    fi

    # Clean host toolchain (reserved)
    if [ "\${ENABLE_HOST_TOOLCHAIN}" -eq 1 ]; then
        func_restore_host_toolchain
    fi

    func_clean_environment
    echo "distcc has been disabled"
}

#------------------------------------------------------------------------------
# Usage function
#------------------------------------------------------------------------------
func_usage() {
    local script_name=\$(basename \${0})
    echo
    echo "Usage: \${script_name} {enable|disable}"
    echo -e "\n\n"
    echo "Current status: \$([ -f \${DISTCC_PROFILE_FILE} ] && echo 'enabled' || echo 'disabled')"
    echo "Cross toolchain distcc: \$([ \${ENABLE_CROSS_TOOLCHAIN:-0} -eq 1 ] && echo 'enabled' || echo 'disabled')"
    echo "Host toolchain distcc: \$([ \${ENABLE_HOST_TOOLCHAIN:-0} -eq 1 ] && echo 'enabled' || echo 'disabled')"
    echo
    return 1
}

func_check_prerequisites() {
    # Check distcc executable
    if [ ! -x "\${DISTCC_PATH}" ]; then
        echo "Error: distcc not found or not executable"
        return 1
    fi

    # Check distcc directory
    if [ ! -d "\${DISTCC_LINKS_DIR}" ]; then
        echo "Error: Distcc directory \${DISTCC_LINKS_DIR} does not exist"
        return 1
    fi

    return 0
}

func_ensure_root() {
    if [ "$(id -u)" -ne 0 ]; then
        echo "This script requires root privileges. Requesting sudo access..."
        exec sudo "$0" "$@"
    fi
}

main() {
    # Setup environment first
    func_setup_environment

    # Ensure root
    func_ensure_root

    # Check prerequisites
    if ! func_check_prerequisites; then
        echo "Error: distcc is not properly installed"
        exit 1
    fi

    echo -e "\nArgument count: \${#}\n"

    # Show usage if no arguments or help requested
    if [ "\${#}" -ne 1 ] || [ "\${1}" = "-h" ] || [ "\${1}" = "--help" ] || [ "\${1}" = "?" ]; then
        echo -e "\n\\\${#}=\${#}\n"
        func_usage
        exit 0
    fi

    # Process command
    case "\${1}" in
        "enable")
            func_enable_distcc
            ;;
        "disable")
            func_disable_distcc
            ;;
        *)
            echo "Error: Invalid command '\${1}'"
            func_usage
            exit 1
            ;;
    esac
}

# Execute main function with all script arguments
main "\$@"
EOF
}

# Set proper permissions for the generated script
func_set_permissions() {
    echo "Setting executable permissions..."
    chmod +x /usr/local/bin/distcc_switcher.sh
}

# Print installation completion message
func_print_completion() {
    echo "Installation completed. distcc_switcher.sh has been installed to /usr/local/bin/"
    echo "Usage: distcc_switcher.sh {enable|disable}"
}

# Main installation function
main() {
    # Step 1: Install prerequisites
    # func_install_prerequisites

    # Step 2: Generate the switcher script
    func_generate_switcher_script

    # Step 3: Set proper permissions
    func_set_permissions

    # Step 4: Print completion message
    func_print_completion
}

# Execute main installation function
main "$@"