#!/bin/bash




func_preparation() {
    set -e
    set -x

    source /.env
    ##################################################################################################
    # 1st file: hide engine
    # it is used to generate the config file which contains lots of distcc related environment variables
    # RW_SWITCHER_ENGINE_FILE_PATH="/usr/local/bin/distcc/.hide_distcc_switcher_engine.sh"
    RW_SWITCHER_ENGINE_FILE_PATH="/usr/local/bin/distcc_switcher.sh"
    # 2nd file: config file
    # it is used to store the config of distcc switcher
    # e.g., export DISTCC_HOSTS="192.168.xxxxx"
    # RW_SWITCHER_CONFIG_FILE_PATH="/usr/local/bin/distcc/.distcc_switcher_config.sh"
    RW_SWITCHER_CONFIG_FILE_PATH="/etc/profile.d/distcc_switcher_config.sh"
    # 3rd file: surface switcher-obsoleted now!
    # it is used to control from top of all
    # RW_SURFACE_SWITCHER_FILE_PATH="/usr/local/bin/distcc_switcher.sh"
    RW_SURFACE_SWITCHER_FILE_PATH=""
    ##################################################################################################


    # 1. create the distcc directory
    sudo mkdir -p $(dirname ${RW_SWITCHER_ENGINE_FILE_PATH})
    sudo mkdir -p $(dirname ${RW_SWITCHER_CONFIG_FILE_PATH})

    sudo touch ${RW_SWITCHER_ENGINE_FILE_PATH}
    sudo touch ${RW_SWITCHER_CONFIG_FILE_PATH}
    if [ -n "${RW_SURFACE_SWITCHER_FILE_PATH}" ]; then
        sudo touch ${RW_SURFACE_SWITCHER_FILE_PATH}
    fi
}

# Generate the final switcher script
func_generate_switcher_script() {

    echo "######################################################"
    echo "# Generating distcc scripts ..."
    echo "######################################################"
    sudo tee ${RW_SWITCHER_ENGINE_FILE_PATH} > /dev/null << EOF
#!/bin/bash
#==============================================================================
# Distcc Switcher Script
# Generated by install_distcc_switcher.sh
# Donot modify this file, it will be overwritten by install_distcc_switcher.sh
#
# Version: ${PROJECT_VERSION}
# Maintainer: ${PROJECT_MAINTAINER}
# Email: ${PROJECT_EMAIL}
# Copyright: ${PROJECT_COPYRIGHT}
# License: ${PROJECT_LICENSE}
#==============================================================================

#------------------------------------------------------------------------------
# Constants and configurations
#------------------------------------------------------------------------------
lv2_func_setup_environment() {
    set -e
    set -x

    #------------------------------------------------------------------------------
    # Control switches
    #------------------------------------------------------------------------------
    ENABLE_HOST_TOOLCHAIN=0
    ENABLE_CROSS_TOOLCHAIN=1

    #------------------------------------------------------------------------------
    # Distcc behavior control
    #------------------------------------------------------------------------------
    # Performance settings
    RW_BAYTTO_INTERNAL_SERVER_URL="${DISTCC_PORT:+${UBUNTU_SERVER_IP:+${UBUNTU_SERVER_IP}:${DISTCC_PORT}}}"
    RW_DISTCC_HOSTS="\${RW_BAYTTO_INTERNAL_SERVER_URL:-localhost/2}"
    RW_DISTCC_PATH="\${PATH}"

    RW_CROSS_TOOLCHAIN_DIR="${SDK_INSTALL_PATH:+${SDK_INSTALL_PATH}/prebuilts/gcc/linux-x86/aarch64/gcc-arm-10.3-2021.07-x86_64-aarch64-none-linux-gnu/bin}"
    RW_BACKUP_DIR="${VOLUMES_ROOT}/backup"

    #------------------------------------------------------------------------------
    # Toolchain configurations
    #------------------------------------------------------------------------------
    RW_CROSS_TOOLCHAIN_NAMES=(
        "aarch64-none-linux-gnu"
        "aarch64-rockchip1031-linux-gnu"
    )
    RW_TOOLCHAIN_COMMANDS=(
        "gcc"
        "g++"
        "c++"
        "cpp"
    )
}


#------------------------------------------------------------------------------
# Usage function
#------------------------------------------------------------------------------
lv2_func_usage() {
    local script_name=\$(basename \${0})
    echo
    echo "Usage: \${script_name} {enable|disable}"
    echo -e "\n\n"
    echo "Current status: \$([ -f ${RW_SWITCHER_CONFIG_FILE_PATH} ] && echo 'enabled' || echo 'disabled')"
    echo "Cross toolchain distcc: \$([ \${ENABLE_CROSS_TOOLCHAIN:-0} -eq 1 ] && echo 'enabled' || echo 'disabled')"
    echo "Host toolchain distcc: \$([ \${ENABLE_HOST_TOOLCHAIN:-0} -eq 1 ] && echo 'enabled' || echo 'disabled')"
    echo -e "\nYou have two ways to use distcc control:"
    echo -e "\n1. Using aliases (Recommended):"
    echo "   distcc-enable    # Enable distcc"
    echo "   distcc-disable   # Disable distcc"
    echo "   To activate aliases now: source /etc/profile.d/distcc_alias.sh"
    echo -e "\n2. Using the original script:"
    echo "   source /usr/local/bin/distcc_switcher.sh enable    # Enable distcc"
    echo "   source /usr/local/bin/distcc_switcher.sh disable   # Disable distcc"
    echo -e "\nNote: Aliases will be automatically available in new terminal sessions."
    echo
    return 1
}

#------------------------------------------------------------------------------
# Environment Config file processing
#------------------------------------------------------------------------------
lv2_func_initial_distcc_config_file() {
    echo "Setting up environment variables..."

    sudo tee ${RW_SWITCHER_CONFIG_FILE_PATH} > /dev/null << EOPROFILE
# Set up distcc configuration
export DISTCC_HOSTS="\${RW_DISTCC_HOSTS:-localhost/2}"
export DISTCC_PATH="\${RW_DISTCC_PATH}"
EOPROFILE

    sudo chmod +x ${RW_SWITCHER_CONFIG_FILE_PATH}

    # make all environments take effect
    if [ -f ${RW_SWITCHER_CONFIG_FILE_PATH} ]; then
        source ${RW_SWITCHER_CONFIG_FILE_PATH}
    else
        echo "Warning: Failed to create profile file"
        return 1
    fi
}

lv2_func_uninitial_distcc_config_file() {
    echo "Cleaning environment..."
    sudo rm -f ${RW_SWITCHER_CONFIG_FILE_PATH}
}


#------------------------------------------------------------------------------
# Host toolchain related functions (reserved interfaces)
#------------------------------------------------------------------------------
lv2_func_setup_host_toolchain() {
    if [ "\${ENABLE_HOST_TOOLCHAIN}" -eq 0 ]; then
        echo "Host toolchain distcc is disabled"
        return 0
    fi
    echo "Empty now, will add host toolchain setup later"
}

lv2_func_restore_host_toolchain() {
    if [ "\${ENABLE_HOST_TOOLCHAIN}" -eq 0 ]; then
        return 0
    fi
    echo "Empty now, will add host toolchain cleanup later"
}

#------------------------------------------------------------------------------
# Cross toolchain related functions
#------------------------------------------------------------------------------
lv2_func_setup_cross_toolchain() {
    if [ "\${ENABLE_CROSS_TOOLCHAIN}" -eq 0 ]; then
        echo "Cross toolchain distcc is disabled"
        return 0
    fi

    # echo "Setting up cross toolchain symlinks..."
    # cd \${RW_DISTCC_LINKS_DIR}

    for prefix in "\${RW_CROSS_TOOLCHAIN_NAMES[@]}"; do
        for cmd in "\${RW_TOOLCHAIN_COMMANDS[@]}"; do
            if [ -d "\${RW_CROSS_TOOLCHAIN_DIR}" ]; then
                # sudo mkdir -p \${RW_BACKUP_DIR}
                # sudo chown "\${DEV_USERNAME}:\${DEV_GROUP}" \${RW_BACKUP_DIR} -R
                # cp -fv "\${RW_CROSS_TOOLCHAIN_DIR}/\${prefix}-\${cmd}" "\${RW_BACKUP_DIR}"
                # rm -f "\${RW_CROSS_TOOLCHAIN_DIR}/\${prefix}-\${cmd}"
                # ln -sf \$(which distcc) "\${RW_CROSS_TOOLCHAIN_DIR}/\${prefix}-\${cmd}"
                echo "sudo mkdir -p \${RW_BACKUP_DIR}"
                echo "sudo chown \${DEV_USERNAME}:\${DEV_GROUP} \${RW_BACKUP_DIR} -R"
                echo "cp -fv \${RW_CROSS_TOOLCHAIN_DIR}/\${prefix}-\${cmd} \${RW_BACKUP_DIR}"
                echo "rm -f \${RW_CROSS_TOOLCHAIN_DIR}/\${prefix}-\${cmd}"
                echo "ln -sf \$(which distcc) \${RW_CROSS_TOOLCHAIN_DIR}/\${prefix}-\${cmd}"
            else
                echo "Error: Cross toolchain directory \${RW_CROSS_TOOLCHAIN_DIR} does not exist."
                echo -e "\tYou can exec this script again after the sdk of \${CONTAINER_NAME} has been cloned."

                return 1
            fi
        done
    done
}

lv2_func_restore_cross_toolchain() {
    echo "Cleaning cross toolchain symlinks..."
    for prefix in "\${RW_CROSS_TOOLCHAIN_NAMES[@]}"; do
        for cmd in "\${RW_TOOLCHAIN_COMMANDS[@]}"; do
            rm -f "\${RW_CROSS_TOOLCHAIN_DIR}/\${prefix}-\${cmd}"
            cp -fv "\${RW_BACKUP_DIR}/\${prefix}-\${cmd}" "\${RW_CROSS_TOOLCHAIN_DIR}"
        done
    done
}


#------------------------------------------------------------------------------
# Main functionality functions
#------------------------------------------------------------------------------
lv1_func_all_preparations() {
    #------------------------------------------------------------------------------
    # Setup environment first
    #------------------------------------------------------------------------------
    lv2_func_setup_environment

    #------------------------------------------------------------------------------
    # Check if distcc is installed
    # Install it if not installed
    #------------------------------------------------------------------------------
    tmp_result="\$(which distcc)"

    if [ -n "\${tmp_result}" ]; then
        echo "distcc has been installed"
    else
        echo "Installing required packages..."
        sudo apt-get update
        sudo apt-get install -y \
            distcc \
            netcat-openbsd
    fi

    echo "arguments: \$#"

    #------------------------------------------------------------------------------
    # Show usage if no arguments or help requested
    #------------------------------------------------------------------------------
    if [ "\${#}" -ne 1 ] || [ "\${1}" = "-h" ] || [ "\${1}" = "--help" ] || [ "\${1}" = "?" ]; then
        echo -e "\n\\\${#}=\${#}\n"
        lv2_func_usage
        exit 0
    fi
}

lv1_func_enable_distcc() {
    # Enable cross toolchain
    if [ "\${ENABLE_CROSS_TOOLCHAIN}" -eq 1 ]; then
        lv2_func_setup_cross_toolchain
    fi

    # Enable host toolchain (reserved)
    if [ "\${ENABLE_HOST_TOOLCHAIN}" -eq 1 ]; then
        lv2_func_setup_host_toolchain
    fi

    # Initialize distcc config file
    lv2_func_initial_distcc_config_file

    echo -e "\ndistcc has been enabled with selected features!\n"
    echo "-------------------------------------------------------------------"
}

lv1_func_disable_distcc() {
    # Clean cross toolchain
    if [ "\${ENABLE_CROSS_TOOLCHAIN}" -eq 1 ]; then
        lv2_func_restore_cross_toolchain
    fi

    # Clean host toolchain (reserved)
    if [ "\${ENABLE_HOST_TOOLCHAIN}" -eq 1 ]; then
        lv2_func_restore_host_toolchain
    fi

    lv2_func_uninitial_distcc_config_file
    echo "distcc has been disabled"
}

main() {
    lv1_func_all_preparations "\$@"

    # Process command
    case "\${1}" in
        "enable")
            lv1_func_enable_distcc
            ;;
        "disable")
            lv1_func_disable_distcc
            ;;
        *)
            echo "Error: Invalid command '\${1}'"
            lv2_func_usage
            exit 1
            ;;
    esac
}

# Execute main function with all script arguments
main "\$@"
EOF

}

func_set_permissions() {
    echo -e "\nSetting executable permissions..."
    sudo chmod +x ${RW_SWITCHER_ENGINE_FILE_PATH}
    sudo chmod +x ${RW_SWITCHER_CONFIG_FILE_PATH}
    if [ -n "${RW_SURFACE_SWITCHER_FILE_PATH}" ]; then
        sudo chmod +x ${RW_SURFACE_SWITCHER_FILE_PATH}
    fi
    echo -e "\nExecutable permissions have been set successfully!\n"
}

# 修改使用说明
func_print_completion() {
    echo
    echo "###############################################################################"
    echo -e "#    Installation completed. distcc control has been installed.        #"
    echo "###############################################################################"
    echo -e "\nTo use distcc control:"
    echo
    echo "   ${RW_SWITCHER_ENGINE_FILE_PATH} enable     # Enable distcc"
    echo "   ${RW_SWITCHER_ENGINE_FILE_PATH} disable    # Disable distcc"
    echo
}

# Main installation function
main() {
    # Step 1: Install prerequisites
    # func_install_prerequisites
    func_preparation

    # Step 2: Generate the switcher script
    func_generate_switcher_script

    # Step 3: Set proper permissions
    func_set_permissions

    # Step 4: Print completion message
    func_print_completion
}

# Execute main installation function
main "$@"